[package]
name = "senbei-android-metadata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "IL2CPP metadata restoration for Senbei Android"

[dependencies]
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
