[package]
name = "senbei-android-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Protector container primitives for Senbei Android"

[dependencies]
aes.workspace = true
thiserror.workspace = true

[lints]
workspace = true
