[package]
name = "senbei-android-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Filesystem and CLI orchestration for Senbei Android"

[dependencies]
anyhow.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
zip.workspace = true
senbei-android-elf.workspace = true
senbei-android-metadata.workspace = true
senbei-android-engine.workspace = true

[lints]
workspace = true
