[package]
name = "senbei-web"
version = "1.1.0"
edition = "2024"
description = "WebAssembly browser frontend for senbei"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
senbei-io = { path = "../senbei-io" }
senbei-metadata = { path = "../senbei-metadata" }
senbei-pe = { path = "../senbei-pe" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
